apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: values-prod.yaml  # or a ConfigMapGenerator/SecretGenerator with overrides

namespace: my-app-prod
