apiVersion: v1
kind: Service
metadata:
  name: file-stream-app-service
  namespace: file-stream-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  selector:
    app: file-stream-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80