apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-fdl-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  environment: dev
          - git:
              repoURL: git@github.com:asoltes/fdl-app-helm-charts.git
              revision: HEAD
              directories:
                - path: charts/*
  template:
    metadata:
      name: "fdl-{{path.basename}}"
    spec:
      project: default
      sources:
        - repoURL: git@github.com:asoltes/fdl-app-helm-charts.git
          targetRevision: feat/argocd
          path: charts/*
          helm:
            valueFiles:
              - $values/dev/values-dev.yaml

        
        - repoURL: git@github.com:asoltes/fdl-app-config.git
          targetRevision: HEAD
          ref: values

      destination:
        server: "{{server}}"   # From clusters generator
        namespace: "fdl-{{path.basename}}"  # Optional: Customize per env
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
