apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-fdl-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  environment: dev
          - git:
              repoURL: git@github.com:asoltes/fdl-app-config.git
              revision: HEAD
              directories:
                - path: environments/*
  template:
    metadata:
      name: "fdl-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:asoltes/fdl-app-config.git
        targetRevision: HEAD
        path: "{{path}}"
        kustomize: {}   # 👈 Explicitly use Kustomize instead of Helm
      destination:
        server: "{{server}}"   # From clusters generator
        namespace: "fdl-{{path.basename}}"  # Optional: Customize per env
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
