apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-fdl-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  environment: prod
          - git:
              repoURL: git@github.com:asoltes/fdl-app-helm-charts.git
              revision: feat/argocd
              directories:
                - path: charts/*
  template:
    metadata:
      name: "prod-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:asoltes/fdl-app-helm-charts.git
        targetRevision: feat/argocd
        path: "{{path}}"
        helm:
          valueFiles:
            - ../environments/prod/values-prod.yaml
      destination:
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
