apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-stream-app-ingress
  namespace: file-stream-app

spec:
  ingressClassName: traefik
  rules:
    - host: dev.andrestrek.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: file-stream-app-service
                port:
                  number: 80