apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-stream-app-ingress
  namespace: file-stream-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: file-stream-app-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: dev.andrestrek.com
