apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ets-
nameSuffix: -dev

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: file-stream-app-ingress
