apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # - ingress-patch.yaml

namePrefix: ets-
nameSuffix: -dev

patches:
  - target:
        group: networking.k8s.io
        version: v1
        kind: Ingress
        name: file-stream-app-ingress
    path: ingress-patch.yaml

