name: dev-fdl-app
replicaCount: 2
image:
  repository: asoltes/file-download-stream
  tag: v3.3.0
  pullPolicy: Always

namespace: file-download-app
awsSecretName: aws-credentials

ingress:
  enabled: true
  className: traefik
  host: dev.andrestrek.com
  entrypoints: web
  middlewares: fdl-app-forward-auth@kubernetescrd
  path: /
  pathType: Prefix

service:
  port: 80
  targetPort: 80

middleware:
  forwardAuth:
    address: https://httpbin.org/basic-auth/dev/passwd
